type Snippet @collection(name: "snippets") {
  name: String!
  content: String!
  public: Boolean!
  url: String!
  user: User!
}

type User @collection(name: "users") {
  name: String!
  email: String!
  idNetlifyIdentity: String!
}

# input SubmitOrderProductInput {
#   productId: ID!
#   quantity: Int!
# }

type Query {
  allSnippets: [Snippet!]! @index(name: "all_snippets")
  allUsers: [User!]! @index(name: "all_users")
}

# type Mutation {
#   submitOrder(customerId: ID!, products: [SubmitOrderProductInput]): Order! @resolver(name: "submit_order")
# }