type Snippet @collection(name: "snippets") {
  name: String!
  content: String!
  public: Boolean!
  user: User!
}

type User @collection(name: "users") {
  name: String!
  email: String! @unique
  idNetlifyIdentity: String! @unique
  snippets: [Snippet] @relation
}

type Query {
  findUserByIdNetlifyIdentity(idNetlifyIdentity: String!): User
}